### ISSUE TITLE
Requirement 

### ISSUE THREAD

**Issue by mjavadhpour** [hamed-shirbandi/AzManCofee#1]
How to install **NetSqlAzman.exe** and where is it in the windows 8 or any other? can I use `azman.mcs` instead?

**Comment by mjavadhpour** [comment]
The application name is Net SQL Authorization Manager Console, and I think that this application cannot find on the internet because it was too old. I see the [NetSqlAzMan](https://github.com/JamesTryand/NetSqlAzMan) and I think that application exists in the repository and developers should compile build her/his own console.

**Comment by hamed-shirbandi** [comment]
sorry for late!
you can download the compatible version of NetSqlAzMan [here](https://github.com/hamed-shirbandi/AzManCofee/raw/master/netsqlazman5%266.rar)
